services:
  app:
    build: .
    container_name: tarot-app
    environment:
      # Flask port inside the container
      - PORT=5000
      # Inside the container we save to /data/saves; bind mount maps host path -> this dir
      - PATH_TO_SAVE=/data/saves
      # Optional: pass your OpenAI key from your host env or .env file next to this compose file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      # Mount your host save directory (same PATH_TO_SAVE you use locally) into /data/saves in the container
      - ${PATH_TO_SAVE:-/tmp/tarot_saves}:/data/saves
    restart: unless-stopped


